### ISSUE TITLE
Bug on switching community from private to public

### ISSUE THREAD

**Issue by lifenautjoe** [OkunaOrg/okuna-api#668]
> An Okuna user found a bug that occurs when switching a community from private to public. If you happened to deactivate the option for community members to invite new members into a private community and then switch the community to public, this setting is kept active. Meaning ppl can't invite new members to a public community and the owner can't change this setting unless he switches back to private, adjusts the setting accordingly and switches back to public again.
> I could confirm and recreate this behavior in a test community I created for this purpose. (edited)

**Comment by uiboy** [comment]
hmm 🤔 i thought we were going to disable changing communities from private to public... since it could compromise comments people shared in confidence. I understand some groups may start private n then decide to go public... but we have to think about how to handle that. 
Some ideas (but needs more thought in a separate issue)
-  could be consensus via an agree button from the members to go public ( not scalable beyond 50 members) 
- Option to have their community activity n data deleted when it goes public but stay in the community

**Comment by lifenautjoe** [comment]
Ah right.

Then nvm this issue. Should be made about restricting private communities
from being made public

**Comment by uiboy** [comment]
Made a new issue as discussed : https://github.com/OkunaOrg/okuna-api/issues/670 
closing this
