### ISSUE TITLE
What the password for django ?

### ISSUE THREAD

**Issue by Maj3styy** [OkunaOrg/okuna-api#669]

**Comment by engmsaleh** [comment]
I need this also, I didn't find it anywhere :(

**Comment by lifenautjoe** [comment]
Have you run the initial test data migrations? If so, the test accounts are in the README file. Otherwise the app will have no accounts. You need to generate a registration token using the create_invite command https://github.com/OkunaOrg/okuna-api#managepy-create_invite and register using the API or from the mobile app.
