### ISSUE TITLE
AttributeError: 'module' object has no attribute 'run'

### ISSUE THREAD

**Issue by Paranormaly** [OkunaOrg/okuna-api#725]
After installing the requirements I run "python okuna-cli.py up-full" and got this error.

`Traceback (most recent call last):
  File "okuna-cli.py", line 405, in <module>
    cli()
  File "/home/mike/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/mike/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/mike/.local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mike/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mike/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "okuna-cli.py", line 327, in up_services_only
    subprocess.run(["docker-compose", "-f", "docker-compose-services-only.yml", "up", "-d", "-V"])
AttributeError: 'module' object has no attribute 'run'`

**Comment by Komposten** [comment]
Not sure if it is related to this particular issue, but try running it with Python 3.5 or above (mentioned as a requirement [here](https://github.com/OkunaOrg/okuna-api#installation)).

**Comment by Paranormaly** [comment]
Thanks for pointing me for this..python 3.8 already installed but the server was using python 2.7 I used this trick to switch to python 3 [How to make 'python' program command execute Python 3](https://askubuntu.com/questions/320996/how-to-make-python-program-command-execute-python-3)
but now I got another error which is 

`/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.25.9) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Usage: okuna-cli.py [OPTIONS] COMMAND [ARGS]...

Error: No such command "up-full".
`
I'm not a python expert . I'm running okuna api on local vm using ubuntu server 18.04

**Comment by Komposten** [comment]
A couple of suggestions:
1) Make sure you used Python 3's pip when you installed the packages. It will by default be `pip3` rather than just `pip` (the latter refers to Python 2.7's pip).
2) If installing the requirements using pip3 doesn't work, try the solutions provided here: https://stackoverflow.com/questions/50202238/python-pip-requestsdependencywarning-urllib3-1-9-1-or-chardet-2-3-0-doe

-----
I booted up an Ubuntu Desktop VM and tried running Okuna CLI there. After getting Docker set up everything seems to run as 
expected. And for the record, the requirements near the top of the README file are for running the API server directly. If you use Okuna CLI those requirements are installed automatically in the Docker container.

**Comment by Paranormaly** [comment]
@Komposten  Thank you so much. I reset everything in the server and started by installing only python3 and pip3 and things went perfect.
I hope someone edit the README to mention such a thing. things are not clear about using pip3.
Anyway thankx
